// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2v0tdxhWxx-7yyQQKuFyqRwyMeaDs8Ss',
    appId: '1:127347556472:web:50cb1ab4a696ba58ba2d8d',
    messagingSenderId: '127347556472',
    projectId: 'textarct',
    authDomain: 'textarct.firebaseapp.com',
    storageBucket: 'textarct.firebasestorage.app',
    measurementId: 'G-3CSP0R5M10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEllS3rY65pg6F39li0fjTMYSidAjxso',
    appId: '1:127347556472:android:defa1cf1b59c36fdba2d8d',
    messagingSenderId: '127347556472',
    projectId: 'textarct',
    storageBucket: 'textarct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5XZuafqAiHyyxTNgXj78r89J2qJjL5w',
    appId: '1:127347556472:ios:404e41c92bcf816bba2d8d',
    messagingSenderId: '127347556472',
    projectId: 'textarct',
    storageBucket: 'textarct.firebasestorage.app',
    iosBundleId: 'com.example.textract',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5XZuafqAiHyyxTNgXj78r89J2qJjL5w',
    appId: '1:127347556472:ios:404e41c92bcf816bba2d8d',
    messagingSenderId: '127347556472',
    projectId: 'textarct',
    storageBucket: 'textarct.firebasestorage.app',
    iosBundleId: 'com.example.textract',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2v0tdxhWxx-7yyQQKuFyqRwyMeaDs8Ss',
    appId: '1:127347556472:web:9f70e99f7505ecafba2d8d',
    messagingSenderId: '127347556472',
    projectId: 'textarct',
    authDomain: 'textarct.firebaseapp.com',
    storageBucket: 'textarct.firebasestorage.app',
    measurementId: 'G-8852NP5PF6',
  );
}
